- DATASET:
    ALIGN_LIMS: null
    ARRAY_SELECT: ALL
    BIN_SIZE: 2
    CONDITION_SEP_FIELD: null
    EXCLUDE_CHANNELS: []
    EXCLUDE_CONDITIONS: []
    EXCLUDE_TRIALS: []
    NAME: NP_AAV6-2_ReaChR_184500
    SPK_KEEP_THRESHOLD: null
    SPK_XCORR_THRESHOLD: 0.1
- CHOP_PARAMETERS:
    CHOP_MARGINS: 0
    DATA_FIELDNAME: spikes
    EXT_INPUT_FIELDNAME: ''
    MAX_OFFSET: 0
    OVERLAP: 50
    RANDOM_SEED: 0
    TYPE: spikes
    USE_EXT_INPUT: false
    WINDOW: 200
